spring:
  r2dbc:
    url: r2dbc:${DATABASE_URL}?sslMode=require
    pool:
      initial-size: 10
      max-size: 50
      max-idle-time: 30m
  
  data:
    redis:
      host: ec2-3-221-18-61.compute-1.amazonaws.com
      port: 31480
      password: p7bfc323da351a0b2f83af32880d1357003d3049198b705845d3615bb1ee7004c
      connect-timeout: 60000
      client-name: r2-web-flux

  main:
    allow-bean-definition-overriding: true

  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}
            scope:
              - user:email
              - read:user
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
        provider:
          github:
            authorization-uri: https://github.com/login/oauth/authorize
            token-uri: https://github.com/login/oauth/access_token
            user-info-uri: https://api.github.com/user

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    disable-swagger-default-url: true
    theme: material
    doc-expansion: list
    operations-sorter: alpha
    tags-sorter: alpha

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  level:
    root: INFO
    com.gomin.r2webflux: DEBUG
    org.springframework.r2dbc: DEBUG
    io.r2dbc.postgresql.QUERY: DEBUG

server:
  port: ${PORT:8080}
  forward-headers-strategy: native
  base-url: https://r2-web-flux-8a261ca95b28.herokuapp.com

jwt:
  secret: ${JWT_SECRET_KEY:your_jwt_secret_key_must_be_at_least_32_bytes_long}
  expiration: ${JWT_EXPIRATION:86400000}