spring:
  r2dbc:
    url: r2dbc:${DATABASE_URL}?sslMode=require&ssl=true
    pool:
      initial-size: 10
      max-size: 50
      max-idle-time: 30m
    properties:
      ssl: true
      sslMode: require
      sslRootCert: false
  
  data:
    redis:
      host: ec2-3-221-18-61.compute-1.amazonaws.com
      port: 31480
      password: p7bfc323da351a0b2f83af32880d1357003d3049198b705845d3615bb1ee7004c
      connect-timeout: 60000
      client-name: r2-web-flux

  main:
    allow-bean-definition-overriding: true  # 빈 오버라이딩을 허용하는 방법이지만, 위의 통합 방식을 추천합니다

  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}
            scope:
              - user:email
              - read:user
            redirect-uri: ${APP_URL:http://localhost:8080}/login/oauth2/code/github
        provider:
          github:
            authorization-uri: https://github.com/login/oauth/authorize
            token-uri: https://github.com/login/oauth/access_token
            user-info-uri: https://api.github.com/user

# OpenAPI (Swagger) Configuration
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    disable-swagger-default-url: true
    url: /v3/api-docs
    theme: material  # 현대적인 Material 테마 사용
    doc-expansion: list  # 문서를 list 형태로 표시
    default-models-expand-depth: 1
    syntax-highlight:
      theme: nord  # 현대적인 Nord 테마의 코드 하이라이팅
    filter: true  # 검색 필터 활성화
    operations-sorter: alpha  # 알파벳 순 정렬
    tags-sorter: alpha  # 태그 알파벳 순 정렬
    display-operation-id: false
    default-model-rendering: model

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  level:
    root: INFO
    com.gomin.r2webflux: DEBUG
    org.springframework:
      jpa: DEBUG
      data.redis: DEBUG
    org.hibernate.SQL: DEBUG
    org.springframework.r2dbc: DEBUG
    io.r2dbc.postgresql: DEBUG
    io.r2dbc.postgresql.QUERY: DEBUG
    io.r2dbc.postgresql.PARAM: DEBUG

server:
  port: ${PORT:8080}  # Use PORT environment variable, fallback to 8080 if not set

jwt:
  secret: ${JWT_SECRET_KEY:your_jwt_secret_key_must_be_at_least_32_bytes_long}
  expiration: ${JWT_EXPIRATION:86400000}  # 24hours, 기본값 추가